#include <stdio.h>

#include <fstream>
#include <iostream>
#include <string>

#include "../include/helpers.h"
#include "../include/inputparser.h"
#include "../include/keypair.h"
#include "../include/kyber.h"

#ifdef __cplusplus
extern "C" {
#endif

#include "../kyber/ref/rng.h"

#ifdef __cplusplus
}
#endif

#define SEED_BYTES 48

#define NOT_EQUAL 0
#define EQUAL 1
#define ERROR 2

enum FileType { pk, sk, ct, ss };

std::string getValue(std::ifstream* const file, const std::string marker) {
    std::string line;
    while (getline(*file, line)) {
        std::size_t pos = line.find(marker);
        if (pos != std::string::npos) return line.substr(pos + marker.length());
    }
    return "";
}

/*
    Converts a hex string into a byte array.
*/
void readHex(const std::string in, uint8_t* const out, const int len) {
    memset(out, 0x00, len);

    for (int i = 0; i < in.length(); i++) {
        char ch = in[i];
        if ((ch >= '0') && (ch <= '9'))
            ch = ch - '0';
        else if ((ch >= 'A') && (ch <= 'F'))
            ch = ch - 'A' + 10;
        else if ((ch >= 'a') && (ch <= 'f'))
            ch = ch - 'a' + 10;
        else
            ch = 0;

        for (int j = 0; j < len - 1; j++)
            out[j] = (out[j] << 4) | (out[j + 1] >> 4);
        out[len - 1] = (out[len - 1] << 4) | ch;
    }
}

/*
    Read the value for a specific marker from the kat file and compare it to
    the value from the file generated by the kyber programm.
    Returns 1 if the values are equal.
*/
int test(std::ifstream* const file, const std::string marker, const FileType type,
         const int buf_size) {
    std::string value = getValue(file, marker);
    if (value.empty()) return ERROR;

    uint8_t kat_buf[buf_size];
    readHex(value, kat_buf, buf_size);

    std::string uid;
    uint8_t parsed_buf[buf_size];

    switch (type) {
        case pk:
            if (!parsePKFile(PK_FILE_DEFAULT, parsed_buf, uid)) return ERROR;
            break;
        case sk:
            if (!parseSKFile(SK_FILE_DEFAULT, parsed_buf, uid)) return ERROR;
            break;
        case ct:
            if (!parseCTFile(CT_FILE_DEFAULT, parsed_buf)) return ERROR;
            break;
        case ss:
            if (!parseKeyFile(KEY_FILE_DEFAULT, parsed_buf)) return ERROR;
            break;
        default:
            return ERROR;
    }

    if (memcmp(kat_buf, parsed_buf, buf_size)) return NOT_EQUAL;
    return EQUAL;
}

int main(int argc, char* argv[]) {
    InputParser input(argc, argv);

    const std::string kat_arg = input.getCmdOption("-kat");
    if (kat_arg.empty()) {
        std::cout << "No kat file specified. Please use -kat option to specify "
                     "a kat file."
                  << std::endl;
        return -1;
    }

    std::ifstream kat_file(kat_arg);
    if (!kat_file.is_open()) {
        std::cout << "Unable to open kat file." << std::endl;
        return -1;
    }

    while (!getValue(&kat_file, "count = ").empty()) {
        // retrive the seed from the kat file and use it for initialization
        std::string value = getValue(&kat_file, "seed = ");
        if (value.empty()) {
            std::cout << "error: couldn't retrive seed" << std::endl;
            continue;
        }

        unsigned char seed[SEED_BYTES];
        readHex(value, seed, SEED_BYTES);
        randombytes_init(seed, NULL, 256);

        std::cout << "testing with seed " << value << std::endl;

        // generate the four kyber files
        Keypair pair;
        Kyber kyber;
        kyber.generate(&pair, "test");
        kyber.encrypt(&pair, PK_FILE_DEFAULT);
        kyber.decrypt(&pair, SK_FILE_DEFAULT, CT_FILE_DEFAULT);

        // compare the generated kyber files with the kat file
        if (test(&kat_file, "pk = ", FileType(pk), CRYPTO_PUBLICKEYBYTES) !=
                EQUAL ||
            test(&kat_file, "sk = ", FileType(sk), CRYPTO_SECRETKEYBYTES) !=
                EQUAL ||
            test(&kat_file, "ct = ", FileType(ct), CRYPTO_CIPHERTEXTBYTES) !=
                EQUAL ||
            test(&kat_file, "ss = ", FileType(ss), CRYPTO_BYTES) != EQUAL) {
            std::cout << "error: test was not successful" << std::endl
                      << std::endl;
        } else {
            std::cout << "success" << std::endl << std::endl;
        }
    }

    kat_file.close();
    return 0;
}
